version: '3'
services:

  hours:
    build: .
    volumes:
      - ../:/app
      - ~/.m2/:/home/hours/.m2/
    environment:
      - DB_URL=mongodb://db/hours
      - BROKER_HOST=broker:9092

  broker:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=pending-cmds,succeed-cmds,failed-cmds
  db:
    image: mongo
    ports:
      - "27017:27017"
